version: "2.1"
services:
  jellyfin:
    image: yude/jellyfin
    build: .
    container_name: jellyfin
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [compute, utility, video]
    devices:
      - '/dev/dri:/dev/dri'
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Tokyo
    network_mode: host
    restart: unless-stopped